# Site settings
title: Renraku
email: "&#117;&#107;&#111;&#64;&#117;&#110;&#105;&#107;&#101;&#114;&#110;&#101;&#108;&#46;&#110;&#101;&#116;"
copyright_name: Yuriy Tymchuk
author_url: http://yuriy.tymch.uk/
github_project: Uko/Renraku

baseurl: /Renraku

collections:
- features
- concepts
- projects

# used to estimate reading time
wpm: 150

port: 4444
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
